on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/workflow.yml'
      - 'src/**'

name: Test

env:
  RUSTFLAGS: "-Dwarnings --cfg tracing_unstable"
  RUSTDOCFLAGS: "-Dwarnings"
  RUST_BACKTRACE: "1" 

jobs:
  clippy:
    name: Clippy Check
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
