on:
  workflow_dispatch:
  push:
    branches-ignore: '**' # for normal push events
    paths:
      - '.github/workflows/workflow.yml'
      - 'src/**'
    pull_request:
      types:
        - opened
        - synchronize
        - reopened
      paths:
      - '.github/workflows/workflow.yml'
      - 'src/**'

name: Test

env:
  RUSTFLAGS: "-Dwarnings --cfg tracing_unstable"
  RUSTDOCFLAGS: "-Dwarnings"
  RUST_BACKTRACE: "1" 

jobs:
  clippy:
    name: Clippy Check
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
